name: Publish ib Module

on:
  push:
    branches:
      - main


jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish
        env:
          NUGET_KEY: ${{ secrets.PSGALLERY_NUGET_KEY }}
        shell: pwsh
        run: |
          $moduleVersion=(import-powershellDataFile -Path ./ib.psd1).ModuleVersion
          $PSDefaultParameterValues['*:Encoding']='utf8BOM'
          if ((Find-Module ib).version -ne $moduleVersion) {
              #Nouvelle version : lancer la publication
              Publish-Module -Path ./ib -NuGetApiKey $env:NUGET_KEY -tag 'PSEdition_Desktop','PSEdition_Core','Windows' -iconUri 'https://raw.githubusercontent.com/Ib-Cegos/ibPSModule/refs/heads/main/logo-ib.png' -Verbose
              write-host "::notice title=Publication réussie::Publication de la version $moduleVersion vers la gallerie Powershell"}
          else {write-host "::warning title=Version identique::La version n'a pas changé, pas de publication"}
